# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20170330_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='End Date (Leave blank if                               not required)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time (leave blank if                                not required)'),
        ),
    ]
