# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_past_events_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(verbose_name='Time of Event'),
        ),
    ]
