# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_change_strand_indexes_to_strandpage'),
        ('cms', '0018_image_grid_CharBlock'),
    ]

    operations = [
    ]
