# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailsearch.index


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_auto_20190117_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordEntryWordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Word Type/Part of Speech',
                'verbose_name_plural': 'Word Types/Parts of Speech',
            },
            bases=(wagtail.wagtailsearch.index.Indexed, models.Model),
        ),
        migrations.AlterField(
            model_name='recordentry',
            name='first_attest_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='First                                                Attestation Year'),
        ),
        migrations.AddField(
            model_name='recordentrywordtype',
            name='source',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_type_relationship', to='cms.RecordEntry'),
        ),
        migrations.AddField(
            model_name='recordentrywordtype',
            name='word_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cms.WordType'),
        ),
    ]
