# Generated by Django 2.1.5 on 2019-01-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('cms', '0032_auto_20190124_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordentry',
            name='hist_freq_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.Image'),
        ),
    ]
