# Generated by Django 2.1.5 on 2019-01-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_recordentry_hist_freq_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordentry',
            name='hist_freq_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
