# Generated by Django 2.2.1 on 2019-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_loaded_meanings_refact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordentry',
            name='hist_freq',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Historical Frequency'),
        ),
    ]
