# Generated by Django 2.2.6 on 2019-10-03 10:45

from django.db import migrations
import modelcluster.fields
from cms.models import RecordEntry, RecordPage


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_hist_freq_text_field'),
    ]

    def fk_to_m2m(apps, schema_editor):
        for entry in RecordEntry.objects.all():
            if entry.pos:
                entry.pos_multi.add(entry.pos)

        for page in RecordPage.objects.all():
            if page.latin_pos:
                page.latin_pos_multi.add(page.latin_pos)
    

    def m2m_to_fk(apps, schema_editor):
        # WARNING!!!
        # Since we're going from M2M to FK, we take the first one. We have no
        # way to be more specific than this.
        for entry in RecordEntry.objects.all():
            if entry.pos_multi.all():
                entry.pos = entry.pos_multi.all()[0]
            
            for page in RecordPage.objects.all():
                if page.latin_pos_multi.all():
                    page.latin_pos = page.latin_pos_multi.all()[0]


    operations = [
        migrations.AddField(
            model_name='recordentry',
            name='pos_multi',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.POSLabel'),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='latin_pos_multi',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.POSLabel'),
        ),
        migrations.RunPython(fk_to_m2m, m2m_to_fk),
    ]
