# Generated by Django 2.2.6 on 2019-10-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_auto_20191003_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordentry',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='recordpage',
            name='latin_pos',
        ),
    ]
