# Generated by Django 2.2.6 on 2019-10-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_remove_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordentry',
            old_name='pos_multi',
            new_name='pos',
        ),
        migrations.RenameField(
            model_name='recordpage',
            old_name='latin_pos_multi',
            new_name='latin_pos',
        ),
    ]
