# Generated by Django 2.2.6 on 2019-11-18 15:30

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_char_to_richtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordentry',
            name='collocational_history',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordentry',
            name='semantic_history',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
