# Generated by Django 2.2.7 on 2019-11-22 13:01

import cms.models.streamfield
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_field_variants_on_recordentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordentry',
            name='hist_freq',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('html', wagtail.core.blocks.StructBlock([('html', wagtail.core.blocks.RawHTMLBlock()), ('alignment', cms.models.streamfield.HTMLAlignmentChoiceBlock())], icon='code', label='Raw HTML', required=False))], blank=True, verbose_name='Historical frequency'),
        ),
    ]
