# Generated by Django 2.2.6 on 2019-12-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0044_alter_field_hist_freq_verbose_name_on_recordentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtag',
            name='name',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
