# Generated by Django 2.2.6 on 2019-12-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_eventtag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtag',
            name='name',
        ),
    ]
