# Generated by Django 2.2.7 on 2020-01-08 13:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_remove_eventtag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='strandpage',
            name='events_contextual_information',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
