# Generated by Django 2.2.7 on 2020-01-08 16:29

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0047_strandpage_events_contextual_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='strandpage',
            name='blogs_contextual_information',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strandpage',
            name='news_contextual_information',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
