# Generated by Django 2.2.13 on 2020-06-24 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0049_add_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='guest_author',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='cms.BlogGuestAuthor',
                verbose_name='Guest post author'),
        ),
    ]
