# Generated by Django 2.2.13 on 2020-06-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0051_guest_author_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogguestauthor',
            name='first_name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='blogguestauthor',
            name='last_name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='blogguestauthor',
            name='author_name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
