# Generated by Django 2.2.13 on 2020-06-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_alter_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='guest_author',
            new_name='author',
        ),
    ]
