# Generated by Django 2.2.13 on 2020-06-25 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0055_populate_blog_author_data'),
    ]

    def add_guest_author(apps, schema_editor):
        """Add generic guest author"""
        BlogAuthor = apps.get_model('cms', 'BlogAuthor')
        BlogPost = apps.get_model('cms', 'BlogPost')
        author, created = BlogAuthor.objects.get_or_create(
            author_name='guest'
        )
        for post in BlogPost.objects.filter(guest=True):
            if not post.author:
                post.author = author
                post.save()

    operations = [
        migrations.RunPython(add_guest_author),
    ]
