# Generated by Django 2.2.13 on 2020-06-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0056_add_guest_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, help_text='select guest author or leave blank for default user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.BlogAuthor', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='guest',
            field=models.BooleanField(default=False, help_text='Create new guest author in snippets', verbose_name='Guest Post'),
        ),
    ]
