# Generated by Django 2.2.13 on 2020-07-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0059_carousel_reorder'),
    ]

    def add_slugs(apps, schema_editor):
        BlogAuthor = apps.get_model('cms', 'BlogAuthor')
        for author in BlogAuthor.objects.all():
            author.save()

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='author_slug',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.RunPython(add_slugs),
    ]
